### ISSUE TITLE
WellTypeCode 5J

### ISSUE THREAD

**Issue by steveoh** [agrc/uic-etl#11]
### Steps to reproduce

```
WellTypeDetail with the id: UTEQ82B8DD3673CD1C8E                    
    R1              
        The specified condition was not met for 'Well Type Code'. 5J is not valid.          
```
### Expected behaviour

`5J` should be a valid well type code or map to a valid well type code
### Actual behaviour

`5J` is not in the appendix for well types and fails validation so it doesn't get added to the well detail. Then it fails the epa submission.

**Comment by steveoh** [comment]
The problem with this one @brigsz is that the python maps the well sub type to `5J` and for validation `5J` is not an acceptable value based on the data in the appendix. Valid class 5 wells from what I've pulled out of the appendix fall into the following:

`"5A", "5B", "5C", "5D", "5E", "5F", "5G", "5H", "5I", "5K", "5L", "5X"`

The current python script has the question marks on this mapping which is odd.

``` py
elif inSubClass == 5011: #??
    uicWellCode = "5J"
```

**Comment by steveoh** [comment]
The main question is if `5J` is a valid entry. That's all.

**Comment by brigsz** [comment]
From the Client:
Matt,
Attached is the table for the UICWellSubclassDomain.  I exported the domain to a table then added a 3rd column for the EPA Well Code to which the Utah UIC GDB maps.

You will see that there are a few of the UT well codes that do not map to EPA.  I have also corrected the problem with 5011 which should map to 5A25 not 5J
[UICWellSubClassDomain.xlsx](https://github.com/agrc/uic-etl/files/512444/UICWellSubClassDomain.xlsx)

**Comment by steveoh** [comment]
That list is missing `5033`

The python had `5033` going to 

``` cs
case "5033":
{
    switch (_wellClass)
    {
        case 1:
            return "1C";
        case 5:
            return "5A22";
    }

    return _wellTypeCode;
}
```

**Comment by steveoh** [comment]
`5034` had a clause based on the well class but that is not mentioned in the excel. Should i remove the well class case?

``` cs
                        switch (_wellClass)
                        {
                            case 1:
                                return "1W";
                            case 5:
                                return "5A23";
                        }
```

**Comment by steveoh** [comment]
`5041, 42, 43` are also missing from the excel doc but have values from the python. What do I do with those?

**Comment by brigsz** [comment]
I am adding this comment from the client, but I am still a bit unsure how it all fits at the moment.  I am looking into it.

 At one point, before EPA finalized the Class VI rule for Geologic Sequestration of Carbon Dioxide, they were allowing states to permit pilot carbon sequestration wells as Class I, or Class V.  1C was the well code for the Class I option and I guess 5A22 was the Class V case.  These 2 options should be deleted because now EPA requires that all carbon sequestration wells be permitted as Class VI wells.  

Same thing applies to Drinking Water Treatment Residual injection wells..  If the states classified them as Class I wells the well code was 1W if Class V the well code is 5A23.  I made an executive decision :) that any treatment residual  wells would be Class V so I have not included the Class 1 option (1W) in the Utah UIC database. 

 Back up a bit further in that portion of the python script there is another block of code for 3G and 5L2.  These are two different types of wells.3G - In Situ Gassification and 5L2 - In Situ Fossil Fuel Recovery.  I seem to remember that 3Gs have been banned (or maybe I just want them to be) so I have not included it in the UIC db.  5L2s are still okay.  

These blocks of code should be fixed so that there isn't a choice of well code  based on well class.
