### ISSUE TITLE
NAICS Code Rule 7b

### ISSUE THREAD

**Issue by steveoh** [agrc/uic-etl#18]
> Either a NAICS code (NAICSCode), not exceeding 6 characters in length, or a SICS code (SICSCode), not exceeding 4 characters in length, must be present in the Facility record (FacilityDetail).

From the sample schema

``` xml
<FacilityDetail xmlns="http://www.exchangenetwork.net/schema/uic/2">
<FacilityIdentifier>MEEP000F2</FacilityIdentifier>
<LocalityName>a</LocalityName>
<FacilitySiteName>a</FacilitySiteName>
<FacilityPetitionStatusCode>AP</FacilityPetitionStatusCode>
<LocationAddressStateCode>DC</LocationAddressStateCode>
<FacilityStateIdentifier>bx</FacilityStateIdentifier>
<LocationAddressText>a</LocationAddressText>
<FacilitySiteTypeCode>C</FacilitySiteTypeCode>
<NAICSCode>a</NAICSCode>
<SICCode>a</SICCode>
<LocationAddressPostalCode>aaaaa</LocationAddressPostalCode>
```

Do we need one?

**Comment by brigsz** [comment]
Yes, I believe so. It is nasty!!  Not sure how we will enforce this in the
db.

On Oct 12, 2016, at 5:53 PM, steveoh notifications@github.com wrote:

Either a NAICS code (NAICSCode), not exceeding 6 characters in length, or a
SICS code (SICSCode), not exceeding 4 characters in length, must be present
in the Facility record (FacilityDetail).

From the sample schema

<FacilityDetail xmlns="http://www.exchangenetwork.net/schema/uic/2">
<FacilityIdentifier>MEEP000F2</FacilityIdentifier>
<LocalityName>a</LocalityName>
<FacilitySiteName>a</FacilitySiteName>
<FacilityPetitionStatusCode>AP</FacilityPetitionStatusCode>
<LocationAddressStateCode>DC</LocationAddressStateCode>
<FacilityStateIdentifier>bx</FacilityStateIdentifier>
<LocationAddressText>a</LocationAddressText>
<FacilitySiteTypeCode>C</FacilitySiteTypeCode>
<NAICSCode>a</NAICSCode>
<SICCode>a</SICCode>
<LocationAddressPostalCode>aaaaa</LocationAddressPostalCode>

Do we need one?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/agrc/uic-etl/issues/18, or mute the thread

**Comment by steveoh** [comment]
I don't see a field on the facility table in the db.

**Comment by brigsz** [comment]
I wonder where it is hiding. I remember speaking to the client about it.

On Oct 12, 2016, at 6:08 PM, steveoh notifications@github.com wrote:

I don't see a field on the facility table in the db.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
https://github.com/agrc/uic-etl/issues/18#issuecomment-253374957, or mute
the thread

**Comment by steveoh** [comment]
I had them hidden. There is a NAICSPrimary and Secondary.
